In [5]:
import tensorflow as tf
import tensorflow as tf
x=tf.constant([25.0,40.5,73.8,78.9],shape=[1,4],name='x')
y=tf.constant([7.333,33.9,96,56.89],shape=[1,4],name='y')
with tf.name_scope("mean"):
    with tf.name_scope("mean_x_y"):
        x1=tf.reduce_mean(x)
        y1=tf.reduce_mean(y)
        sess=tf.Session()
    print(sess.run(x1))
    print(sess.run(y1)) 
with tf.name_scope("variance"):
    with tf.name_scope("subtract1"):
        w=tf.subtract(x,x1)
        sess1=tf.Session()
    print(sess1.run(w))
    with tf.name_scope("subtract2"):
        b=tf.subtract(y,y1)
        sess2=tf.Session()
    print(sess2.run(b))
    with tf.name_scope("square_result"):
        m=tf.multiply(w,w)
        sess3=tf.Session()
    print(sess3.run(m))
    with tf.name_scope("scope_summation"):
        var=tf.reduce_sum(m)
        sess4=tf.Session()
    print(sess4.run(var))
with tf.name_scope("covariance"):
    with tf.name_scope("multiply"):
        mul1=tf.multiply(w,b)
        sess5=tf.Session()
    print(sess5.run(mul1))
    with tf.name_scope("scope_summation2"):
        covar=tf.reduce_sum(mul1)
        sess6=tf.Session()
    print(sess6.run(covar))

54.55
48.5308
[[-29.55000305 -14.05000305  19.25        24.34999847]]
[[-41.19775009 -14.63074875  47.46924973   8.35924911]]
[[ 873.20269775  197.40258789  370.5625      592.92242432]]
2034.09
[[ 1217.39367676   205.5620575    913.78308105   203.54769897]]
2540.29
